-- lua/dusk/extras/terminal.lua
-- Terminal emulator theme generator for dusk.nvim
--
-- Generates color config files for: kitty, alacritty, wezterm, ghostty,
-- iterm2, windows-terminal, foot, tmux, and a generic ANSI table.
--
-- USAGE (from Neovim command line):
--   :lua require("dusk.extras.terminal").generate()           -- all variants, all formats
--   :lua require("dusk.extras.terminal").generate("dusk-soft") -- one variant, all formats
--   :lua require("dusk.extras.terminal").generate(nil, "kitty") -- all variants, one format
--   :lua require("dusk.extras.terminal").generate("dusk", "alacritty")
--
-- Files are written to extras/themes/<format>/ relative to the plugin root.
-- If you're using the plugin from a repo, set M.output_root below or pass
-- an output dir as a third argument.
--
-- SHELL USAGE (headless, for CI or dotfile scripts):
--   nvim --headless -c "lua require('dusk.extras.terminal').generate()" -c "qa"

local M = {}

-- ─── Helpers ──────────────────────────────────────────────────────────────────

-- Strip '#' from a hex color string.
local function hex(color)
  return color:gsub("^#", "")
end

-- Write a file, creating parent directories as needed.
local function write_file(path, content)
  -- Create parent dirs
  local dir = path:match("^(.*)/[^/]+$")
  if dir then
    vim.fn.mkdir(dir, "p")
  end
  local f = io.open(path, "w")
  if not f then
    vim.notify("dusk: could not write " .. path, vim.log.levels.ERROR)
    return false
  end
  f:write(content)
  f:close()
  return true
end

-- Find the plugin root (the directory containing this file's ancestors).
local function plugin_root()
  -- __FILE__ isn't available in Lua; use debug.getinfo as a fallback.
  local info = debug.getinfo(1, "S")
  local src = info.source:gsub("^@", "")
  -- src is .../lua/dusk/extras/terminal.lua — go up 4 levels
  return src:match("^(.*)/lua/dusk/extras/terminal%.lua$") or vim.fn.stdpath("data")
end

-- ─── Terminal color slot mapping ──────────────────────────────────────────────
-- Returns a flat table of the 16 ANSI slots + background/foreground/cursor
-- derived from the dusk palette. Same logic as init.lua _set_terminal_colors.
local function build_term_colors(c)
  return {
    -- ANSI normal (0-7)
    color0  = c.bg3,         -- black
    color1  = c.red,         -- red
    color2  = c.green,     -- green 
    color3  = c.yellow,      -- yellow
    color4  = c.blue,        -- blue
    color5  = "#b392f0",     -- magenta (terminal only)
    color6  = c.builtin,     -- cyan
    color7  = c.fg_muted,    -- white

    -- ANSI bright (8-15)
    color8  = c.fg_subtle,   -- bright black
    color9  = c.red,     -- bright red
    color10 = c.green,     -- bright green
    color11 = c.orange,      -- bright yellow
    color12 = c.blue,        -- bright blue
    color13 = "#d2a8ff",     -- bright magenta (terminal only)
    color14 = c.teal,        -- bright cyan
    color15 = c.fg,          -- bright white

    -- Semantic
    background = c.bg,
    foreground = c.fg,
    cursor     = c.fg,
    cursor_text = c.bg,
    selection_bg  = c.sel_bg,
    selection_fg  = c.sel_fg,
    url_color  = c.blue,
  }
end

-- ─── Format generators ────────────────────────────────────────────────────────

local formats = {}

-- kitty -----------------------------------------------------------------------
formats.kitty = {
  ext = "conf",
  generate = function(t, variant)
    local lines = {
      "# dusk.nvim — " .. variant .. " — kitty terminal theme",
      "# https://github.com/yourname/dusk.nvim",
      "# Generated by lua/dusk/extras/terminal.lua",
      "",
      "background              " .. t.background,
      "foreground              " .. t.foreground,
      "cursor                  " .. t.cursor,
      "cursor_text_color       " .. t.cursor_text,
      "selection_background    " .. t.selection_bg,
      "selection_foreground    " .. t.selection_fg,
      "url_color               " .. t.url_color,
      "",
      "# black",
      "color0                  " .. t.color0,
      "color8                  " .. t.color8,
      "# red",
      "color1                  " .. t.color1,
      "color9                  " .. t.color9,
      "# green",
      "color2                  " .. t.color2,
      "color10                 " .. t.color10,
      "# yellow",
      "color3                  " .. t.color3,
      "color11                 " .. t.color11,
      "# blue",
      "color4                  " .. t.color4,
      "color12                 " .. t.color12,
      "# magenta",
      "color5                  " .. t.color5,
      "color13                 " .. t.color13,
      "# cyan",
      "color6                  " .. t.color6,
      "color14                 " .. t.color14,
      "# white",
      "color7                  " .. t.color7,
      "color15                 " .. t.color15,
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- alacritty -------------------------------------------------------------------
formats.alacritty = {
  ext = "toml",
  generate = function(t, variant)
    local lines = {
      "# dusk.nvim — " .. variant .. " — alacritty terminal theme",
      "# https://github.com/yourname/dusk.nvim",
      "# Generated by lua/dusk/extras/terminal.lua",
      "# Place in ~/.config/alacritty/themes/ and import with:",
      '#   import = ["~/.config/alacritty/themes/' .. variant .. '.toml"]',
      "",
      "[colors.primary]",
      'background = "' .. t.background .. '"',
      'foreground = "' .. t.foreground .. '"',
      "",
      "[colors.cursor]",
      'cursor = "' .. t.cursor .. '"',
      'text   = "' .. t.cursor_text .. '"',
      "",
      "[colors.selection]",
      'background = "' .. t.selection_bg .. '"',
      'text       = "' .. t.selection_fg .. '"',
      "",
      "[colors.normal]",
      'black   = "' .. t.color0 .. '"',
      'red     = "' .. t.color1 .. '"',
      'green   = "' .. t.color2 .. '"',
      'yellow  = "' .. t.color3 .. '"',
      'blue    = "' .. t.color4 .. '"',
      'magenta = "' .. t.color5 .. '"',
      'cyan    = "' .. t.color6 .. '"',
      'white   = "' .. t.color7 .. '"',
      "",
      "[colors.bright]",
      'black   = "' .. t.color8  .. '"',
      'red     = "' .. t.color9  .. '"',
      'green   = "' .. t.color10 .. '"',
      'yellow  = "' .. t.color11 .. '"',
      'blue    = "' .. t.color12 .. '"',
      'magenta = "' .. t.color13 .. '"',
      'cyan    = "' .. t.color14 .. '"',
      'white   = "' .. t.color15 .. '"',
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- wezterm ---------------------------------------------------------------------
formats.wezterm = {
  ext = "lua",
  generate = function(t, variant)
    local lines = {
      "-- dusk.nvim — " .. variant .. " — wezterm terminal theme",
      "-- https://github.com/yourname/dusk.nvim",
      "-- Generated by lua/dusk/extras/terminal.lua",
      "-- Usage in wezterm.lua:",
      "--   local dusk = require('path.to." .. variant .. "')",
      "--   config.colors = dusk",
      "",
      "return {",
      '  background    = "' .. t.background .. '",',
      '  foreground    = "' .. t.foreground .. '",',
      "",
      "  cursor_bg     = \"" .. t.cursor .. '",',
      '  cursor_fg     = "' .. t.cursor_text .. '",',
      '  cursor_border = "' .. t.cursor .. '",',
      "",
      '  selection_bg  = "' .. t.selection_bg .. '",',
      '  selection_fg  = "' .. t.selection_fg .. '",',
      "",
      "  ansi = {",
      '    "' .. t.color0 .. '",  -- black',
      '    "' .. t.color1 .. '",  -- red',
      '    "' .. t.color2 .. '",  -- green',
      '    "' .. t.color3 .. '",  -- yellow',
      '    "' .. t.color4 .. '",  -- blue',
      '    "' .. t.color5 .. '",  -- magenta',
      '    "' .. t.color6 .. '",  -- cyan',
      '    "' .. t.color7 .. '",  -- white',
      "  },",
      "",
      "  brights = {",
      '    "' .. t.color8  .. '",  -- bright black',
      '    "' .. t.color9  .. '",  -- bright red',
      '    "' .. t.color10 .. '",  -- bright green',
      '    "' .. t.color11 .. '",  -- bright yellow',
      '    "' .. t.color12 .. '",  -- bright blue',
      '    "' .. t.color13 .. '",  -- bright magenta',
      '    "' .. t.color14 .. '",  -- bright cyan',
      '    "' .. t.color15 .. '",  -- bright white',
      "  },",
      "}",
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- ghostty ---------------------------------------------------------------------
formats.ghostty = {
  ext = "conf",
  -- Ghostty uses a flat key=value format (no #rrggbb, just rrggbb)
  generate = function(t, variant)
    local function g(color) return hex(color) end
    local lines = {
      "# dusk.nvim — " .. variant .. " — ghostty terminal theme",
      "# https://github.com/yourname/dusk.nvim",
      "# Generated by lua/dusk/extras/terminal.lua",
      "# Place in ~/.config/ghostty/themes/" .. variant,
      "",
      "background              = " .. g(t.background),
      "foreground              = " .. g(t.foreground),
      "cursor-color            = " .. g(t.cursor),
      "cursor-text             = " .. g(t.cursor_text),
      "selection-background    = " .. g(t.selection_bg),
      "selection-foreground    = " .. g(t.selection_fg),
      "",
      "palette = 0=" .. g(t.color0),
      "palette = 1=" .. g(t.color1),
      "palette = 2=" .. g(t.color2),
      "palette = 3=" .. g(t.color3),
      "palette = 4=" .. g(t.color4),
      "palette = 5=" .. g(t.color5),
      "palette = 6=" .. g(t.color6),
      "palette = 7=" .. g(t.color7),
      "palette = 8="  .. g(t.color8),
      "palette = 9="  .. g(t.color9),
      "palette = 10=" .. g(t.color10),
      "palette = 11=" .. g(t.color11),
      "palette = 12=" .. g(t.color12),
      "palette = 13=" .. g(t.color13),
      "palette = 14=" .. g(t.color14),
      "palette = 15=" .. g(t.color15),
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- iterm2 ----------------------------------------------------------------------
formats.iterm2 = {
  ext = "itermcolors",
  -- iterm2 uses an Apple plist (XML) format
  generate = function(t, variant)
    -- Convert #rrggbb to r g b floats (0.0–1.0) for plist
    local function plist_color(name, hexcol)
      local r = tonumber(hexcol:sub(2,3), 16) / 255
      local g = tonumber(hexcol:sub(4,5), 16) / 255
      local b = tonumber(hexcol:sub(6,7), 16) / 255
      return table.concat({
        "\t<key>" .. name .. "</key>",
        "\t<dict>",
        "\t\t<key>Color Space</key><string>sRGB</string>",
        "\t\t<key>Red Component</key><real>" .. string.format("%.6f", r) .. "</real>",
        "\t\t<key>Green Component</key><real>" .. string.format("%.6f", g) .. "</real>",
        "\t\t<key>Blue Component</key><real>" .. string.format("%.6f", b) .. "</real>",
        "\t</dict>",
      }, "\n")
    end

    local ansi_names = {
      "Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White",
    }
    local slots = {
      t.color0, t.color1, t.color2, t.color3, t.color4, t.color5, t.color6, t.color7,
      t.color8, t.color9, t.color10, t.color11, t.color12, t.color13, t.color14, t.color15,
    }

    local entries = {
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"',
      '  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
      '<plist version="1.0">',
      "<!-- dusk.nvim — " .. variant .. " — iterm2 terminal theme -->",
      "<!-- https://github.com/yourname/dusk.nvim -->",
      "<dict>",
      plist_color("Background Color", t.background),
      plist_color("Foreground Color", t.foreground),
      plist_color("Cursor Color", t.cursor),
      plist_color("Cursor Text Color", t.cursor_text),
      plist_color("Selection Color", t.selection_bg),
      plist_color("Selected Text Color", t.selection_fg),
      plist_color("Link Color", t.url_color),
    }

    for i, color in ipairs(slots) do
      local idx = i - 1
      local prefix = idx < 8 and "Ansi " .. idx .. " Color" or "Ansi " .. idx .. " Color"
      table.insert(entries, plist_color(prefix, color))
    end

    table.insert(entries, "</dict>")
    table.insert(entries, "</plist>")
    return table.concat(entries, "\n") .. "\n"
  end,
}

-- windows-terminal ------------------------------------------------------------
formats["windows-terminal"] = {
  ext = "json",
  generate = function(t, variant)
    -- JSON snippet that can be pasted into Windows Terminal settings.json
    -- under "schemes": [...]
    local lines = {
      "{",
      '  // dusk.nvim — ' .. variant .. ' — Windows Terminal theme',
      '  // https://github.com/yourname/dusk.nvim',
      '  // Generated by lua/dusk/extras/terminal.lua',
      '  // Paste this object into the "schemes" array in settings.json',
      '  "name": "' .. variant .. '",',
      '  "background": "' .. t.background .. '",',
      '  "foreground": "' .. t.foreground .. '",',
      '  "cursorColor": "' .. t.cursor .. '",',
      '  "selectionBackground": "' .. t.selection_bg .. '",',
      "",
      '  "black":         "' .. t.color0 .. '",',
      '  "red":           "' .. t.color1 .. '",',
      '  "green":         "' .. t.color2 .. '",',
      '  "yellow":        "' .. t.color3 .. '",',
      '  "blue":          "' .. t.color4 .. '",',
      '  "purple":        "' .. t.color5 .. '",',
      '  "cyan":          "' .. t.color6 .. '",',
      '  "white":         "' .. t.color7 .. '",',
      "",
      '  "brightBlack":   "' .. t.color8  .. '",',
      '  "brightRed":     "' .. t.color9  .. '",',
      '  "brightGreen":   "' .. t.color10 .. '",',
      '  "brightYellow":  "' .. t.color11 .. '",',
      '  "brightBlue":    "' .. t.color12 .. '",',
      '  "brightPurple":  "' .. t.color13 .. '",',
      '  "brightCyan":    "' .. t.color14 .. '",',
      '  "brightWhite":   "' .. t.color15 .. '"',
      "}",
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- foot ------------------------------------------------------------------------
formats.foot = {
  ext = "ini",
  generate = function(t, variant)
    local function f(color) return hex(color) end
    local lines = {
      "# dusk.nvim — " .. variant .. " — foot terminal theme",
      "# https://github.com/yourname/dusk.nvim",
      "# Generated by lua/dusk/extras/terminal.lua",
      "# Include in foot.ini with: include=~/.config/foot/themes/" .. variant .. ".ini",
      "",
      "[colors]",
      "background = " .. f(t.background),
      "foreground = " .. f(t.foreground),
      "",
      "# Normal",
      "regular0   = " .. f(t.color0),
      "regular1   = " .. f(t.color1),
      "regular2   = " .. f(t.color2),
      "regular3   = " .. f(t.color3),
      "regular4   = " .. f(t.color4),
      "regular5   = " .. f(t.color5),
      "regular6   = " .. f(t.color6),
      "regular7   = " .. f(t.color7),
      "",
      "# Bright",
      "bright0    = " .. f(t.color8),
      "bright1    = " .. f(t.color9),
      "bright2    = " .. f(t.color10),
      "bright3    = " .. f(t.color11),
      "bright4    = " .. f(t.color12),
      "bright5    = " .. f(t.color13),
      "bright6    = " .. f(t.color14),
      "bright7    = " .. f(t.color15),
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- tmux ------------------------------------------------------------------------
formats.tmux = {
  ext = "conf",
  -- tmux doesn't have native 16-color theming in the same way, but we can
  -- set the 256-color palette overrides and the status bar colors.
  -- This generates a sourced snippet for ~/.tmux.conf.
  generate = function(t, variant)
    local lines = {
      "# dusk.nvim — " .. variant .. " — tmux theme",
      "# https://github.com/yourname/dusk.nvim",
      "# Generated by lua/dusk/extras/terminal.lua",
      "# Add to ~/.tmux.conf: source-file ~/.config/tmux/themes/" .. variant .. ".conf",
      "",
      "# Status bar",
      'set -g status-style "bg=' .. t.background .. ',fg=' .. t.foreground .. '"',
      'set -g status-left-style "bg=' .. t.color3 .. ',fg=' .. t.background .. ',bold"',
      'set -g status-right-style "bg=' .. t.color0 .. ',fg=' .. t.foreground .. '"',
      "",
      "# Window titles",
      'set -g window-status-style "bg=' .. t.background .. ',fg=' .. t.foreground .. '"',
      'set -g window-status-current-style "bg=' .. t.color3 .. ',fg=' .. t.background .. ',bold"',
      "",
      "# Pane borders",
      'set -g pane-border-style "fg=' .. t.color0 .. '"',
      'set -g pane-active-border-style "fg=' .. t.color3 .. '"',
      "",
      "# Message / command line",
      'set -g message-style "bg=' .. t.color3 .. ',fg=' .. t.background .. '"',
      "",
      "# Selection in copy mode",
      'set -g mode-style "bg=' .. t.selection_bg .. ',fg=' .. t.selection_fg .. '"',
    }
    return table.concat(lines, "\n") .. "\n"
  end,
}

-- ─── Public API ───────────────────────────────────────────────────────────────

-- Returns a list of all supported format names.
function M.list_formats()
  local names = {}
  for k in pairs(formats) do
    table.insert(names, k)
  end
  table.sort(names)
  return names
end

-- Generate theme files.
-- variant_name: string or nil (nil = all variants)
-- format_name:  string or nil (nil = all formats)
-- output_dir:   string or nil (nil = plugin root / extras/themes)
function M.generate(variant_name, format_name, output_dir)
  local variants_mod = require("dusk.variants")
  local palette_mod  = require("dusk.palette")

  -- Determine which variants to generate
  local variant_list
  if variant_name then
    variant_list = { variant_name }
  else
    variant_list = variants_mod.list()
  end

  -- Determine which formats to generate
  local format_list
  if format_name then
    if not formats[format_name] then
      vim.notify(
        "dusk: unknown format '" .. format_name .. "'. Available: "
        .. table.concat(M.list_formats(), ", "),
        vim.log.levels.ERROR
      )
      return
    end
    format_list = { format_name }
  else
    format_list = M.list_formats()
  end

  -- Output root
  local root = output_dir or (plugin_root() .. "/extras/themes")

  local generated = {}

  for _, vname in ipairs(variant_list) do
    local c = palette_mod.get(vname)
    local t = build_term_colors(c)

    for _, fname in ipairs(format_list) do
      local fmt = formats[fname]
      local content = fmt.generate(t, vname)
      local path = root .. "/" .. fname .. "/" .. vname .. "." .. fmt.ext
      if write_file(path, content) then
        table.insert(generated, path)
      end
    end
  end

  if #generated > 0 then
    vim.notify(
      "dusk: generated " .. #generated .. " file(s):\n  "
      .. table.concat(generated, "\n  "),
      vim.log.levels.INFO
    )
  end

  return generated
end

-- Convenience: generate a single format for a single variant and return the
-- content as a string without writing to disk. Useful for testing.
function M.preview(variant_name, format_name)
  variant_name = variant_name or "dusk"
  format_name  = format_name  or "kitty"
  local fmt = formats[format_name]
  if not fmt then
    return nil, "unknown format: " .. format_name
  end
  local c = require("dusk.palette").get(variant_name)
  local t = build_term_colors(c)
  return fmt.generate(t, variant_name)
end

return M
