-- dusk: plugin highlight groups
-- Covers: telescope, nvim-tree, neo-tree, lualine, gitsigns, nvim-cmp,
--         blink.cmp, fzf-lua, indent-blankline, which-key, and more.
--
-- Selection philosophy: selections must be VISIBLE. No transparent or near-bg colors.
-- All pickers and completion menus use sel_bg (#2a3241) — a clear blue-tinted surface
-- that reads against the near-black bg without being garish.

local M = {}

function M.get(c)
  return {
    -- ─── Telescope ────────────────────────────────────────────────────────────
    TelescopeNormal         = { fg = c.fg,        bg = c.bg_popup },
    TelescopeBorder         = { fg = c.border,    bg = c.bg_popup },
    TelescopePromptNormal   = { fg = c.fg,        bg = c.bg1 },
    TelescopePromptBorder   = { fg = c.border_hi, bg = c.bg1 },
    TelescopePromptTitle    = { fg = c.bg,        bg = c.yellow },
    TelescopeResultsTitle   = { fg = c.bg,        bg = c.border },
    TelescopePreviewTitle   = { fg = c.bg,        bg = c.teal },
    TelescopePromptPrefix   = { fg = c.yellow },
    TelescopePromptCounter  = { fg = c.fg_muted },
    TelescopeSelection      = { fg = c.sel_fg,    bg = c.sel_bg },
    TelescopeSelectionCaret = { fg = c.yellow,    bg = c.sel_bg },
    TelescopeMultiSelection = { fg = c.yellow,    bg = c.bg3 },
    TelescopeMultiIcon      = { fg = c.yellow },
    TelescopeMatching       = { fg = c.yellow,    bold = true },
    TelescopePreviewNormal  = { fg = c.fg,        bg = c.bg },
    TelescopePreviewBorder  = { fg = c.border,    bg = c.bg },
    TelescopeResultsNormal  = { fg = c.fg,        bg = c.bg_popup },
    TelescopeResultsBorder  = { fg = c.border,    bg = c.bg_popup },
    TelescopeResultsDiffAdd     = { fg = c.git_add },
    TelescopeResultsDiffChange  = { fg = c.git_change },
    TelescopeResultsDiffDelete  = { fg = c.git_del },

    -- ─── fzf-lua ──────────────────────────────────────────────────────────────
    FzfLuaNormal            = { fg = c.fg,        bg = c.bg_popup },
    FzfLuaBorder            = { fg = c.border,    bg = c.bg_popup },
    FzfLuaTitle             = { fg = c.bg,        bg = c.yellow },
    FzfLuaPreviewNormal     = { fg = c.fg,        bg = c.bg },
    FzfLuaPreviewBorder     = { fg = c.border,    bg = c.bg },
    FzfLuaPreviewTitle      = { fg = c.bg,        bg = c.teal },
    FzfLuaCursor            = { fg = c.bg,        bg = c.yellow },
    FzfLuaCursorLine        = { fg = c.sel_fg,    bg = c.sel_bg },
    FzfLuaCursorLineNr      = { fg = c.yellow,    bg = c.sel_bg },
    FzfLuaSearch            = { fg = c.bg,        bg = c.yellow },
    FzfLuaScrollBorderEmpty = { fg = c.border },
    FzfLuaScrollBorderFull  = { fg = c.border_hi },
    FzfLuaScrollFloatEmpty  = { fg = c.border },
    FzfLuaScrollFloatFull   = { fg = c.border_hi },
    FzfLuaHelpNormal        = { fg = c.fg_muted,  bg = c.bg1 },
    FzfLuaHelpBorder        = { fg = c.border,    bg = c.bg1 },
    FzfLuaBufName           = { fg = c.yellow },
    FzfLuaBufNr             = { fg = c.fg_muted },
    FzfLuaBufFlagCur        = { fg = c.yellow },
    FzfLuaBufFlagAlt        = { fg = c.fg_muted },
    FzfLuaTabTitle          = { fg = c.yellow,    bold = true },
    FzfLuaTabMarker         = { fg = c.yellow },
    FzfLuaLspWord           = { fg = c.sel_fg,    bg = c.sel_bg },

    -- ─── Nvim-tree ────────────────────────────────────────────────────────────
    NvimTreeNormal          = { fg = c.fg_muted, bg = c.bg1 },
    NvimTreeNormalNC        = { fg = c.fg_muted, bg = c.bg1 },
    NvimTreeEndOfBuffer     = { fg = c.bg1 },
    NvimTreeWinSeparator    = { fg = c.border,   bg = c.bg1 },
    NvimTreeCursorLine      = { bg = c.sel_bg },
    NvimTreeIndentMarker    = { fg = c.border },
    NvimTreeRootFolder      = { fg = c.yellow,   bold = true },
    NvimTreeFolderName      = { fg = c.fg_muted },
    NvimTreeFolderIcon      = { fg = c.yellow },
    NvimTreeOpenedFolderIcon= { fg = c.yellow },
    NvimTreeEmptyFolderName = { fg = c.fg_subtle },
    NvimTreeOpenedFolderName= { fg = c.fg },
    NvimTreeFileName        = { fg = c.fg },
    NvimTreeOpenedFile      = { fg = c.yellow },
    NvimTreeExecFile        = { fg = c.func },
    NvimTreeSpecialFile     = { fg = c.yellow,   underline = true },
    NvimTreeImageFile       = { fg = c.fg_muted },
    NvimTreeSymlink         = { fg = c.builtin },
    NvimTreeGitDirty        = { fg = c.git_change },
    NvimTreeGitNew          = { fg = c.git_add },
    NvimTreeGitDeleted      = { fg = c.git_del },
    NvimTreeGitStaged       = { fg = c.git_add },
    NvimTreeGitMerge        = { fg = c.warn },
    NvimTreeGitRenamed      = { fg = c.git_change },
    NvimTreeGitIgnored      = { fg = c.fg_subtle },

    -- ─── Neo-tree ─────────────────────────────────────────────────────────────
    NeoTreeNormal           = { fg = c.fg_muted, bg = c.bg1 },
    NeoTreeNormalNC         = { fg = c.fg_muted, bg = c.bg1 },
    NeoTreeDirectoryIcon    = { fg = c.yellow },
    NeoTreeRootName         = { fg = c.yellow,   bold = true },
    NeoTreeFileName         = { fg = c.fg },
    NeoTreeFileIcon         = { fg = c.fg_muted },
    NeoTreeGitAdded         = { fg = c.git_add },
    NeoTreeGitModified      = { fg = c.git_change },
    NeoTreeGitDeleted       = { fg = c.git_del },
    NeoTreeGitIgnored       = { fg = c.fg_subtle },
    NeoTreeDotfile          = { fg = c.fg_subtle },
    NeoTreeCursorLine       = { bg = c.sel_bg },
    NeoTreeIndentMarker     = { fg = c.border },
    NeoTreeEndOfBuffer      = { fg = c.bg1 },
    NeoTreeWinSeparator     = { fg = c.border, bg = c.bg1 },

    -- ─── Lualine (base groups — lualine theme in extras/lualine.lua) ──────────
    StatusLine              = { fg = c.fg_muted,  bg = c.bg3 },
    StatusLineNC            = { fg = c.fg_subtle, bg = c.bg3 },

    -- ─── Gitsigns ─────────────────────────────────────────────────────────────
    GitSignsAdd             = { fg = c.git_add },
    GitSignsChange          = { fg = c.git_change },
    GitSignsDelete          = { fg = c.git_del },
    GitSignsAddNr           = { fg = c.git_add },
    GitSignsChangeNr        = { fg = c.git_change },
    GitSignsDeleteNr        = { fg = c.git_del },
    GitSignsAddLn           = { bg = "#122b1e" },
    GitSignsChangeLn        = { bg = "#1a2635" },
    GitSignsDeleteLn        = { bg = "#2a1a1a" },
    GitSignsCurrentLineBlame= { fg = c.fg_subtle },

    -- ─── nvim-cmp ─────────────────────────────────────────────────────────────
    CmpNormal               = { fg = c.fg,        bg = c.bg_popup },
    CmpBorder               = { fg = c.border,    bg = c.bg_popup },
    CmpDocNormal            = { fg = c.fg,        bg = c.bg1 },
    CmpDocBorder            = { fg = c.border,    bg = c.bg1 },
    CmpItemAbbr             = { fg = c.fg },
    CmpItemAbbrMatch        = { fg = c.yellow,    bold = true },
    CmpItemAbbrMatchFuzzy   = { fg = c.yellow },
    CmpItemAbbrDeprecated   = { fg = c.fg_subtle, strikethrough = true },
    CmpItemMenu             = { fg = c.fg_subtle },
    CmpItemSelected         = { fg = c.sel_fg,    bg = c.sel_bg },
    CmpItemKindText         = { fg = c.fg },
    CmpItemKindMethod       = { fg = c.func },
    CmpItemKindFunction     = { fg = c.func },
    CmpItemKindConstructor  = { fg = c.func },
    CmpItemKindField        = { fg = c.text },
    CmpItemKindVariable     = { fg = c.text },
    CmpItemKindClass        = { fg = c.text },
    CmpItemKindInterface    = { fg = c.text },
    CmpItemKindModule       = { fg = c.text },
    CmpItemKindProperty     = { fg = c.text },
    CmpItemKindUnit         = { fg = c.constant },
    CmpItemKindValue        = { fg = c.constant },
    CmpItemKindEnum         = { fg = c.text },
    CmpItemKindKeyword      = { fg = c.keyword },
    CmpItemKindSnippet      = { fg = c.yellow },
    CmpItemKindColor        = { fg = c.orange },
    CmpItemKindFile         = { fg = c.fg_muted },
    CmpItemKindReference    = { fg = c.fg_muted },
    CmpItemKindFolder       = { fg = c.yellow },
    CmpItemKindEnumMember   = { fg = c.constant },
    CmpItemKindConstant     = { fg = c.constant },
    CmpItemKindStruct       = { fg = c.text },
    CmpItemKindEvent        = { fg = c.keyword },
    CmpItemKindOperator     = { fg = c.op },
    CmpItemKindTypeParameter= { fg = c.text },

    -- ─── blink.cmp ────────────────────────────────────────────────────────────
    BlinkCmpMenu                = { fg = c.fg,        bg = c.bg_popup },
    BlinkCmpMenuBorder          = { fg = c.border,    bg = c.bg_popup },
    BlinkCmpMenuSelection       = { fg = c.sel_fg,    bg = c.sel_bg },
    BlinkCmpScrollBarThumb      = { bg = c.border_hi },
    BlinkCmpScrollBarGutter     = { bg = c.bg3 },
    BlinkCmpLabel               = { fg = c.fg },
    BlinkCmpLabelMatch          = { fg = c.yellow,    bold = true },
    BlinkCmpLabelDetail         = { fg = c.fg_muted },
    BlinkCmpLabelDescription    = { fg = c.fg_subtle },
    BlinkCmpLabelDeprecated     = { fg = c.fg_subtle, strikethrough = true },
    BlinkCmpKind                = { fg = c.fg_muted },
    BlinkCmpSource              = { fg = c.fg_subtle },
    BlinkCmpGhostText           = { fg = c.fg_subtle },
    BlinkCmpDoc                 = { fg = c.fg,        bg = c.bg1 },
    BlinkCmpDocBorder           = { fg = c.border,    bg = c.bg1 },
    BlinkCmpDocSeparator        = { fg = c.border },
    BlinkCmpDocCursorLine       = { bg = c.sel_bg },
    BlinkCmpSignatureHelp       = { fg = c.fg,        bg = c.bg1 },
    BlinkCmpSignatureHelpBorder = { fg = c.border,    bg = c.bg1 },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.yellow, underline = true },
    BlinkCmpKindText            = { fg = c.fg },
    BlinkCmpKindMethod          = { fg = c.func },
    BlinkCmpKindFunction        = { fg = c.func },
    BlinkCmpKindConstructor     = { fg = c.func },
    BlinkCmpKindField           = { fg = c.text },
    BlinkCmpKindVariable        = { fg = c.text },
    BlinkCmpKindClass           = { fg = c.text },
    BlinkCmpKindInterface       = { fg = c.text },
    BlinkCmpKindModule          = { fg = c.text },
    BlinkCmpKindProperty        = { fg = c.text },
    BlinkCmpKindUnit            = { fg = c.constant },
    BlinkCmpKindValue           = { fg = c.constant },
    BlinkCmpKindEnum            = { fg = c.text },
    BlinkCmpKindKeyword         = { fg = c.keyword },
    BlinkCmpKindSnippet         = { fg = c.yellow },
    BlinkCmpKindColor           = { fg = c.orange },
    BlinkCmpKindFile            = { fg = c.fg_muted },
    BlinkCmpKindReference       = { fg = c.fg_muted },
    BlinkCmpKindFolder          = { fg = c.yellow },
    BlinkCmpKindEnumMember      = { fg = c.constant },
    BlinkCmpKindConstant        = { fg = c.constant },
    BlinkCmpKindStruct          = { fg = c.text },
    BlinkCmpKindEvent           = { fg = c.keyword },
    BlinkCmpKindOperator        = { fg = c.op },
    BlinkCmpKindTypeParameter   = { fg = c.text },

    -- ─── Indent Blankline (v2 + v3) ───────────────────────────────────────────
    IblIndent               = { fg = c.border },
    IblScope                = { fg = c.border_hi },
    IblWhitespace           = { fg = c.border },
    IndentBlanklineChar                 = { fg = c.border },
    IndentBlanklineContextChar          = { fg = c.border_hi },
    IndentBlanklineSpaceChar            = { fg = c.border },
    IndentBlanklineSpaceCharBlankline   = { fg = c.border },

    -- ─── Which-key ────────────────────────────────────────────────────────────
    WhichKey                = { fg = c.yellow },
    WhichKeyGroup           = { fg = c.func },
    WhichKeyDesc            = { fg = c.fg },
    WhichKeySeparator       = { fg = c.fg_subtle },
    WhichKeyValue           = { fg = c.fg_muted },
    WhichKeyBorder          = { fg = c.border,    bg = c.bg_popup },
    WhichKeyFloat           = { bg = c.bg_popup },
    WhichKeyTitle           = { fg = c.bg,        bg = c.yellow },
    WhichKeyNormal          = { fg = c.fg,        bg = c.bg_popup },

    -- ─── Mason ────────────────────────────────────────────────────────────────
    MasonNormal             = { fg = c.fg,        bg = c.bg_popup },
    MasonHighlight          = { fg = c.yellow },
    MasonHighlightBlock     = { fg = c.bg,        bg = c.yellow },
    MasonHighlightBlockBold = { fg = c.bg,        bg = c.yellow, bold = true },
    MasonMuted              = { fg = c.fg_muted },
    MasonMutedBlock         = { fg = c.fg_muted,  bg = c.bg3 },
    MasonError              = { fg = c.error },

    -- ─── Lazy.nvim ────────────────────────────────────────────────────────────
    LazyNormal              = { fg = c.fg,        bg = c.bg_popup },
    LazyBorder              = { fg = c.border,    bg = c.bg_popup },
    LazyButton              = { fg = c.fg,        bg = c.bg3 },
    LazyButtonActive        = { fg = c.bg,        bg = c.yellow, bold = true },
    LazyH1                  = { fg = c.bg,        bg = c.yellow, bold = true },
    LazyH2                  = { fg = c.yellow,    bold = true },
    LazyProp                = { fg = c.fg_muted },
    LazyValue               = { fg = c.string },
    LazyUrl                 = { fg = c.blue,      underline = true },
    LazyProgressDone        = { fg = c.yellow },
    LazyProgressTodo        = { fg = c.fg_subtle },
    LazySpecial             = { fg = c.yellow },

    -- ─── Flash.nvim ───────────────────────────────────────────────────────────
    FlashBackdrop           = { fg = c.fg_subtle },
    FlashMatch              = { fg = c.fg,        bg = c.bg3 },
    FlashCurrent            = { fg = c.bg,        bg = c.yellow, bold = true },
    FlashLabel              = { fg = c.bg,        bg = c.red,    bold = true },
    FlashPrompt             = { fg = c.fg,        bg = c.bg1 },

    -- ─── Trouble.nvim ─────────────────────────────────────────────────────────
    TroubleNormal           = { fg = c.fg,        bg = c.bg1 },
    TroubleNormalNC         = { fg = c.fg_muted,  bg = c.bg1 },
    TroubleCount            = { fg = c.yellow },
    TroubleError            = { fg = c.error },
    TroubleWarning          = { fg = c.warn },
    TroubleInfo             = { fg = c.info },
    TroubleHint             = { fg = c.hint },
    TroubleText             = { fg = c.fg },
    TroubleFile             = { fg = c.yellow },
    TroublePos              = { fg = c.fg_muted },
    TroubleIndent           = { fg = c.border },
    TroubleIconError        = { fg = c.error },
    TroubleIconWarn         = { fg = c.warn },
    TroubleIconInfo         = { fg = c.info },
    TroubleIconHint         = { fg = c.hint },

    -- ─── Notify ───────────────────────────────────────────────────────────────
    NotifyERRORBorder       = { fg = c.error },
    NotifyWARNBorder        = { fg = c.warn },
    NotifyINFOBorder        = { fg = c.info },
    NotifyDEBUGBorder       = { fg = c.fg_subtle },
    NotifyTRACEBorder       = { fg = c.fg_subtle },
    NotifyERRORIcon         = { fg = c.error },
    NotifyWARNIcon          = { fg = c.warn },
    NotifyINFOIcon          = { fg = c.info },
    NotifyERRORTitle        = { fg = c.error,     bold = true },
    NotifyWARNTitle         = { fg = c.warn,      bold = true },
    NotifyINFOTitle         = { fg = c.info,      bold = true },
    NotifyERRORBody         = { fg = c.fg },
    NotifyWARNBody          = { fg = c.fg },
    NotifyINFOBody          = { fg = c.fg },

    -- ─── Noice ────────────────────────────────────────────────────────────────
    NoiceCmdlinePopup           = { fg = c.fg,        bg = c.bg_popup },
    NoiceCmdlinePopupBorder     = { fg = c.border_hi, bg = c.bg_popup },
    NoiceCmdlineIcon            = { fg = c.yellow },
    NoiceConfirm                = { fg = c.fg,        bg = c.bg_popup },
    NoiceConfirmBorder          = { fg = c.yellow },
    NoiceLspProgressTitle       = { fg = c.yellow },
    NoiceLspProgressClient      = { fg = c.fg_muted },
    NoiceLspProgressSpinner     = { fg = c.yellow },

    -- ─── Snacks.nvim (folke/snacks.nvim) ──────────────────────────────────────
    SnacksPickerNormal          = { fg = c.fg,        bg = c.bg_popup },
    SnacksPickerBorder          = { fg = c.border,    bg = c.bg_popup },
    SnacksPickerTitle           = { fg = c.bg,        bg = c.yellow },
    SnacksPickerSearch          = { fg = c.bg,        bg = c.yellow },
    SnacksPickerSelected        = { fg = c.yellow },
    SnacksPickerCursor          = { fg = c.bg,        bg = c.yellow },
    SnacksPickerListCursorLine  = { fg = c.sel_fg,    bg = c.sel_bg },
    SnacksPickerPreviewNormal   = { fg = c.fg,        bg = c.bg },
    SnacksPickerPreviewBorder   = { fg = c.border,    bg = c.bg },
    SnacksPickerPreviewTitle    = { fg = c.bg,        bg = c.teal },
    SnacksPickerMatch           = { fg = c.yellow,    bold = true },
    SnacksDashboardNormal       = { fg = c.fg,        bg = c.bg },
    SnacksDashboardHeader       = { fg = c.yellow },
    SnacksDashboardTitle        = { fg = c.yellow,    bold = true },
    SnacksDashboardDesc         = { fg = c.fg_muted },
    SnacksDashboardIcon         = { fg = c.yellow },
    SnacksDashboardKey          = { fg = c.red },
    SnacksDashboardFooter       = { fg = c.fg_subtle },
    SnacksDashboardSpecial      = { fg = c.fg_muted },
    SnacksDashboardDir          = { fg = c.fg_subtle },
    SnacksNotifierInfo          = { fg = c.info },
    SnacksNotifierWarn          = { fg = c.warn },
    SnacksNotifierError         = { fg = c.error },
    SnacksNotifierDebug         = { fg = c.fg_muted },
    SnacksNotifierTrace         = { fg = c.fg_subtle },
    SnacksIndent                = { fg = c.border },
    SnacksIndentScope           = { fg = c.border_hi },

    -- ─── Aerial.nvim ──────────────────────────────────────────────────────────
    AerialNormal            = { fg = c.fg_muted,  bg = c.bg1 },
    AerialLine              = { fg = c.sel_fg,    bg = c.sel_bg },
    AerialGuide             = { fg = c.border },

    -- ─── Navic ────────────────────────────────────────────────────────────────
    NavicIconsFile          = { fg = c.fg_muted },
    NavicIconsModule        = { fg = c.text },
    NavicIconsNamespace     = { fg = c.text },
    NavicIconsPackage       = { fg = c.text },
    NavicIconsClass         = { fg = c.text },
    NavicIconsMethod        = { fg = c.func },
    NavicIconsProperty      = { fg = c.text },
    NavicIconsField         = { fg = c.text },
    NavicIconsConstructor   = { fg = c.func },
    NavicIconsEnum          = { fg = c.text },
    NavicIconsInterface     = { fg = c.text },
    NavicIconsFunction      = { fg = c.func },
    NavicIconsVariable      = { fg = c.text },
    NavicIconsConstant      = { fg = c.constant },
    NavicIconsString        = { fg = c.string },
    NavicIconsNumber        = { fg = c.constant },
    NavicIconsBoolean       = { fg = c.keyword },
    NavicIconsArray         = { fg = c.text },
    NavicIconsObject        = { fg = c.text },
    NavicIconsKey           = { fg = c.keyword },
    NavicIconsNull          = { fg = c.builtin },
    NavicIconsEnumMember    = { fg = c.constant },
    NavicIconsStruct        = { fg = c.text },
    NavicIconsEvent         = { fg = c.keyword },
    NavicIconsOperator      = { fg = c.op },
    NavicIconsTypeParameter = { fg = c.text },
    NavicText               = { fg = c.fg_muted },
    NavicSeparator          = { fg = c.fg_subtle },

    -- ─── Mini.nvim ────────────────────────────────────────────────────────────
    MiniCursorword              = { bg = c.bg2, underline = true },
    MiniCursorwordCurrent       = { bg = c.bg2, underline = true },
    MiniPickNormal              = { fg = c.fg,        bg = c.bg_popup },
    MiniPickBorder              = { fg = c.border,    bg = c.bg_popup },
    MiniPickBorderText          = { fg = c.yellow,    bg = c.bg_popup },
    MiniPickBorderBusy          = { fg = c.fg_muted,  bg = c.bg_popup },
    MiniPickCursor              = { fg = c.bg,        bg = c.yellow },
    MiniPickMatchCurrent        = { fg = c.sel_fg,    bg = c.sel_bg },
    MiniPickMatchMarked         = { fg = c.yellow,    bg = c.bg3 },
    MiniPickMatchRanges         = { fg = c.yellow,    bold = true },
    MiniPickHeader              = { fg = c.yellow,    bold = true },
    MiniPickIconDirectory       = { fg = c.yellow },
    MiniPickIconFile            = { fg = c.fg_muted },
    MiniPickPrompt              = { fg = c.yellow },
    MiniStatuslineFilename      = { fg = c.fg_muted,  bg = c.bg3 },
    MiniStatuslineDevinfo       = { fg = c.fg_muted,  bg = c.bg3 },
    MiniStatuslineFileinfo      = { fg = c.fg_muted,  bg = c.bg3 },
    MiniStatuslineModeNormal    = { fg = c.bg,        bg = c.yellow, bold = true },
    MiniStatuslineModeInsert    = { fg = c.bg,        bg = c.blue,   bold = true },
    MiniStatuslineModeVisual    = { fg = c.bg,        bg = c.orange, bold = true },
    MiniStatuslineModeCommand   = { fg = c.bg,        bg = c.red,    bold = true },
    MiniStatuslineModeReplace   = { fg = c.bg,        bg = c.red,    bold = true },
    MiniStatuslineInactive      = { fg = c.fg_subtle, bg = c.bg3 },

    -- ─── Render-markdown.nvim ─────────────────────────────────────────────────
    RenderMarkdownH1            = { fg = c.yellow,    bold = true, bg = "#1c1e14" },
    RenderMarkdownH2            = { fg = c.func,      bold = true, bg = "#141a1c" },
    RenderMarkdownH3            = { fg = c.text,      bold = true },
    RenderMarkdownCode          = { bg = c.bg1 },
    RenderMarkdownCodeInline    = { fg = c.string,    bg = c.bg1 },
    RenderMarkdownBullet        = { fg = c.op },
    RenderMarkdownQuote         = { fg = c.fg_muted },
    RenderMarkdownDash          = { fg = c.border_hi },
    RenderMarkdownTableHead     = { fg = c.yellow,    bold = true },
    RenderMarkdownTableRow      = { fg = c.fg },
    RenderMarkdownTableFill     = { fg = c.border },
    RenderMarkdownChecked       = { fg = c.fg_subtle },
    RenderMarkdownUnchecked     = { fg = c.fg_muted },

    -- ─── vim-illuminate ───────────────────────────────────────────────────────
    IlluminatedWordText         = { bg = c.bg2 },
    IlluminatedWordRead         = { bg = c.bg2 },
    IlluminatedWordWrite        = { bg = c.bg2, underline = true },
  }
end

return M
