-- dusk.nvim — dusk-break — wezterm terminal theme
-- https://github.com/yourname/dusk.nvim
-- Generated by lua/dusk/extras/terminal.lua
-- Usage in wezterm.lua:
--   local dusk = require('path.to.dusk-break')
--   config.colors = dusk

return {
  background    = "#262427",
  foreground    = "#f0ece0",

  cursor_bg     = "#f0ece0",
  cursor_fg     = "#262427",
  cursor_border = "#f0ece0",

  selection_bg  = "#3a3f46",
  selection_fg  = "#f0ece0",

  ansi = {
    "#38363d",  -- black
    "#e57068",  -- red
    "#8fbf8f",  -- green
    "#f6c177",  -- yellow
    "#7da6d1",  -- blue
    "#b392f0",  -- magenta
    "#79c2cc",  -- cyan
    "#a29aa4",  -- white
  },

  brights = {
    "#6c6670",  -- bright black
    "#e57068",  -- bright red
    "#8fbf8f",  -- bright green
    "#d4956a",  -- bright yellow
    "#7da6d1",  -- bright blue
    "#d2a8ff",  -- bright magenta
    "#79c2cc",  -- bright cyan
    "#f0ece0",  -- bright white
  },
}
