-- dusk.nvim — dusk — wezterm terminal theme
-- https://github.com/yourname/dusk.nvim
-- Generated by lua/dusk/extras/terminal.lua
-- Usage in wezterm.lua:
--   local dusk = require('path.to.dusk')
--   config.colors = dusk

return {
  background    = "#0d1117",
  foreground    = "#dcd7ba",

  cursor_bg     = "#dcd7ba",
  cursor_fg     = "#0d1117",
  cursor_border = "#dcd7ba",

  selection_bg  = "#2a3241",
  selection_fg  = "#dcd7ba",

  ansi = {
    "#21262d",  -- black
    "#ff7b72",  -- red
    "#8dba8d",  -- green
    "#e6c384",  -- yellow
    "#79c0ff",  -- blue
    "#b392f0",  -- magenta
    "#7dcfff",  -- cyan
    "#8b949e",  -- white
  },

  brights = {
    "#4d5566",  -- bright black
    "#ff7b72",  -- bright red
    "#8dba8d",  -- bright green
    "#c9956a",  -- bright yellow
    "#79c0ff",  -- bright blue
    "#d2a8ff",  -- bright magenta
    "#7dcfff",  -- bright cyan
    "#dcd7ba",  -- bright white
  },
}
