-- dusk.nvim — dusk-dawn — wezterm terminal theme
-- https://github.com/yourname/dusk.nvim
-- Generated by lua/dusk/extras/terminal.lua
-- Usage in wezterm.lua:
--   local dusk = require('path.to.dusk-dawn')
--   config.colors = dusk

return {
  background    = "#1e2228",
  foreground    = "#dcd7ba",

  cursor_bg     = "#dcd7ba",
  cursor_fg     = "#1e2228",
  cursor_border = "#dcd7ba",

  selection_bg  = "#35424f",
  selection_fg  = "#dcd7ba",

  ansi = {
    "#30373f",  -- black
    "#e57068",  -- red
    "#8dba8d",  -- green
    "#e6c384",  -- yellow
    "#79c0ff",  -- blue
    "#b392f0",  -- magenta
    "#7dcfff",  -- cyan
    "#8b949e",  -- white
  },

  brights = {
    "#526070",  -- bright black
    "#e57068",  -- bright red
    "#8dba8d",  -- bright green
    "#e8956a",  -- bright yellow
    "#79c0ff",  -- bright blue
    "#d2a8ff",  -- bright magenta
    "#7dcfff",  -- bright cyan
    "#dcd7ba",  -- bright white
  },
}
